import { Component } from "@angular/core";
@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  
  showData: boolean;

  assetsData;

  aseetsResponseData = [
    {
      name: "TENET HEALTHCARE CORPORATION",
      taBusSoldID: {
        expand: false,
        "21623": [
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UDR4",
            amount: "748371.5295",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UF2G",
            amount: "2239414.8761",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UN2C",
            amount: "6038939.9500",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UG70",
            amount: "709244.7645",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UDS1",
            amount: "2269226.8964",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UD8O",
            amount: "5148920.4066",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U2V5",
            amount: "21690625.1238",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U62K",
            amount: "2998494.6932",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UE26",
            amount: "4360133.4066",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U9LO",
            amount: "1554358.0177",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UYCR",
            amount: "2162384.4498",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UDR9",
            amount: "42890.1907",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U2N2",
            amount: "1259710.5813",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U3AC",
            amount: "1845387.5214",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "USX7",
            amount: "2512436.9959",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UDR7",
            amount: "1249506.8520",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U32Z",
            amount: "4902602.0929",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UDR6",
            amount: "5205813.0768",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UGT4",
            amount: "9259676.8800",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UG74",
            amount: "68205.4489",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U3Z1",
            amount: "18435218.6381",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U318",
            amount: "4362657.7951",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UD8N",
            amount: "2780910.1521",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UWFJ",
            amount: "2575129.0005",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U2V8",
            amount: "4739206.2413",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UG73",
            amount: "883851.6510",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UG72",
            amount: "2318869.3230",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UDR8",
            amount: "901199.7428",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "U2W3",
            amount: "3476283.1129",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2006 DCP",
            fundCode: "UG71",
            amount: "3731907.7012",
            taSystem: "F",
            ta: "FPRS",
          },
        ],
        "21624": [
          {
            fundName: "TENET 2001 DCP",
            fundCode: "USX7",
            amount: "5841.9194",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UYCR",
            amount: "2238.7200",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U318",
            amount: "14581.1668",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U9LO",
            amount: "11505.8858",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UWFJ",
            amount: "159020.9495",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U3Z1",
            amount: "514324.7114",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U62K",
            amount: "9564.4248",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UD8N",
            amount: "5146.5121",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UN2C",
            amount: "544436.4500",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U2W3",
            amount: "4610.0722",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U2V5",
            amount: "1558827.6953",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UE26",
            amount: "35558.0430",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UGT4",
            amount: "115713.2000",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "U32Z",
            amount: "10884.8851",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UDS1",
            amount: "223166.6994",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UD8O",
            amount: "146031.6441",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 2001 DCP",
            fundCode: "UF2G",
            amount: "14823.6581",
            taSystem: "F",
            ta: "FPRS",
          },
        ],
        "25100": [
          {
            fundName: "TENET 401(K)",
            fundCode: "1282",
            amount: "37938.9800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3405",
            amount: "594.2100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFAG",
            amount: "2047.3000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBG2",
            amount: "775.6300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FC0Z",
            amount: "5680.8300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OQBZ",
            amount: "4989.9900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDVQ",
            amount: "358430.1300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0818",
            amount: "59808.6600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FH2B",
            amount: "10886.1100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OSX7",
            amount: "85776011.4172",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0352",
            amount: "10397.9400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0094",
            amount: "1044.5100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TG72",
            amount: "512137136.7720",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGMK",
            amount: "89326.0200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OQLV",
            amount: "47714.2800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGVE",
            amount: "185709.4600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHGF",
            amount: "83566.0700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDOD",
            amount: "106424.5100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0353",
            amount: "30280.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OFJ3",
            amount: "363.4000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0314",
            amount: "100822.6100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAUX",
            amount: "24499.2400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBA9",
            amount: "74568.1500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHDG",
            amount: "488459.8300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0338",
            amount: "77492.4700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBS6",
            amount: "2280.7200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0315",
            amount: "4857.7500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0507",
            amount: "17903.9900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "O9LO",
            amount: "102687117.2794",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2326",
            amount: "58827.5100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0514",
            amount: "2965.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0096",
            amount: "4906.0000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBKW",
            amount: "1269.9900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAG5",
            amount: "6894.5900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1617",
            amount: "9960.5900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0333",
            amount: "15490.1000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFLO",
            amount: "2945.4300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OFN1",
            amount: "14489.2400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2120",
            amount: "52018.1900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2348",
            amount: "424.8400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OSHF",
            amount: "58376.6900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3231",
            amount: "84473.9400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFCH",
            amount: "7906.5500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2418",
            amount: "27905.7500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OKAO",
            amount: "20988.9200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OSM6",
            amount: "1005.9600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FD4I",
            amount: "2035.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3227",
            amount: "522710.6700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0060",
            amount: "532501.9200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0005",
            amount: "8606.7200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDW3",
            amount: "18144.0500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0708",
            amount: "49.3100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFIY",
            amount: "4560.8000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0318",
            amount: "63984703.1023",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OMCD",
            amount: "32067.1400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FA7U",
            amount: "16015.5300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0324",
            amount: "2567.3800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHJ0",
            amount: "14081.0600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDKX",
            amount: "15869.9100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAST",
            amount: "31558.4200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TG70",
            amount: "327511359.1147",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFZ8",
            amount: "181231.1500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBUG",
            amount: "13696.9400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCCC",
            amount: "114215.4100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGDD",
            amount: "1722.3600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDDZ",
            amount: "93836.3900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1329",
            amount: "446891.1300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGVM",
            amount: "222342.5300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBQ3",
            amount: "9571.8800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2328",
            amount: "798093.8000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FA7E",
            amount: "43393.8400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OMKD",
            amount: "7844.6400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGE5",
            amount: "948.2000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAKO",
            amount: "4537.4200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OFSL",
            amount: "8395.8500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FEA1",
            amount: "1456.0700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0517",
            amount: "9692.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FB9Z",
            amount: "19711.9800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGQG",
            amount: "15397.3400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "BOND",
            amount: "728832.7700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGOL",
            amount: "16345.9400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FA68",
            amount: "60109.1200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1827",
            amount: "22522.3500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OSUN",
            amount: "66179.1500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDBO",
            amount: "18488.8700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3988",
            amount: "96678626.9569",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFAR",
            amount: "1865.2400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHDH",
            amount: "361546.6000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDGM",
            amount: "332000.7300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FC9Q",
            amount: "4970.1000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAHH",
            amount: "68641.1000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TF2G",
            amount: "89670842.2948",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHO7",
            amount: "96183.0300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDMA",
            amount: "50562.0500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGVF",
            amount: "380164.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGVG",
            amount: "190947.8000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDHP",
            amount: "96805.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0300",
            amount: "118244.2700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OE5H",
            amount: "11293.7900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCNW",
            amount: "5085.2200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHKU",
            amount: "3172.3800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0009",
            amount: "10734.2800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "NFMF",
            amount: "3869081.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAPH",
            amount: "27370.3800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3404",
            amount: "1207.4100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0065",
            amount: "3809.1500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2365",
            amount: "6922.8100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0330",
            amount: "5055.7200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHO5",
            amount: "42333.9300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0021",
            amount: "2743015.1900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2352",
            amount: "120421.9300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1315",
            amount: "115792.8400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAIG",
            amount: "46840.7400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDKU",
            amount: "80490.9000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FB01",
            amount: "2007.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFJH",
            amount: "127220.1400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FC11",
            amount: "224729.1000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHF5",
            amount: "3238.0400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2358",
            amount: "137204.7500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0046",
            amount: "127062.4300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TDR4",
            amount: "170616971.2982",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0814",
            amount: "18442.4900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3963",
            amount: "62690844.4591",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHO6",
            amount: "92661.3100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1271",
            amount: "15778.0400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OELQ",
            amount: "43619.9900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHHE",
            amount: "24235.3900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FH12",
            amount: "3979.5800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDOR",
            amount: "962.7500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OMKH",
            amount: "10774.1100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0372",
            amount: "403479.0800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OTHR",
            amount: "87293.0000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0055",
            amount: "30931375.5900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHEG",
            amount: "314724.5300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3047",
            amount: "24477.2800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3403",
            amount: "1459.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0505",
            amount: "12118.8600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFQJ",
            amount: "27590.9000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDKC",
            amount: "49215.6700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "O32Z",
            amount: "170645118.5131",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCV3",
            amount: "7441.7700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0331",
            amount: "290.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHSL",
            amount: "127316.8400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAXM",
            amount: "6669.9200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHEC",
            amount: "404783.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1958",
            amount: "23.7300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OFZR",
            amount: "31448.3100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0963",
            amount: "4222.1200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OF04",
            amount: "106116.5900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OEZY",
            amount: "6273.3800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHDY",
            amount: "852813.8700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "4005",
            amount: "1036021608.0730",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FD7X",
            amount: "53217.7900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHEB",
            amount: "189261.2700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0580",
            amount: "24280.9800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0820",
            amount: "111810.6000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0066",
            amount: "29186.4700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "GCT4",
            amount: "584671521.1300",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHSN",
            amount: "58616.6400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGU6",
            amount: "22652.0000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAL8",
            amount: "41189.9200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2326",
            amount: "87366062.8313",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBHD",
            amount: "30762.1800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3049",
            amount: "33767.3500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FEGB",
            amount: "24174.9200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3406",
            amount: "16368.2500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHQK",
            amount: "45414.2700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2738",
            amount: "2173.4600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2622",
            amount: "53761.7400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1368",
            amount: "13002.6200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "6511",
            amount: "562235552.3560",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFOK",
            amount: "4971.6400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2338",
            amount: "2805.7900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGMR",
            amount: "11566.5400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2238",
            amount: "29928.2500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHRX",
            amount: "19690.8500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0309",
            amount: "3849.5600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0322",
            amount: "120876.3700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3488",
            amount: "3208.3500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCIQ",
            amount: "8461.8500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OF42",
            amount: "70148.3300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFXH",
            amount: "105013.6200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2344",
            amount: "37272.6500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FAKC",
            amount: "1373.6600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDCX",
            amount: "21528.3600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1314",
            amount: "240006.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDWX",
            amount: "8660.4300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDIO",
            amount: "50052.5400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCE0",
            amount: "282782.7300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FA30",
            amount: "9545.5100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0354",
            amount: "75710.7400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBQ1",
            amount: "5893.6200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDLD",
            amount: "103872.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0093",
            amount: "250151.5900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHOJ",
            amount: "77242.7400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0038",
            amount: "2739379.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBM8",
            amount: "1958.9400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1388",
            amount: "4564.8900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFY0",
            amount: "3.3000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDDQ",
            amount: "32874.9100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCYQ",
            amount: "43991.0700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0022",
            amount: "306256.0500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OFMD",
            amount: "59478.7600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDUS",
            amount: "22049.3700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TD8O",
            amount: "191096574.1918",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TDR6",
            amount: "567482557.3641",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OKW6",
            amount: "7347.3700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0832",
            amount: "6622.3600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGL7",
            amount: "4124.9300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFQI",
            amount: "76533.4500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHDJ",
            amount: "454118.6800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDZH",
            amount: "32613.5600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGS1",
            amount: "6609.1800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FC6S",
            amount: "21170.2500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0337",
            amount: "14839.2100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OIIJ",
            amount: "4749.0400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0042",
            amount: "430541.2700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OSWK",
            amount: "18591.3600",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHVQ",
            amount: "70671.3000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0342",
            amount: "4170.3100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0511",
            amount: "23971.7300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FFUZ",
            amount: "282721.1200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TD8N",
            amount: "95946067.9036",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0041",
            amount: "54172.9400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OF63",
            amount: "6806.2300",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FC4B",
            amount: "9483.2200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FBYK",
            amount: "11903.3900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FCKB",
            amount: "61233.2400",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OFW9",
            amount: "190.9500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0068",
            amount: "47293.4000",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FD3H",
            amount: "64995.3200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0027",
            amount: "7504.3200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2830",
            amount: "63428.2500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDEJ",
            amount: "44710.9700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHAG",
            amount: "1476.2900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OMCE",
            amount: "55492.3500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FDKR",
            amount: "3048.8900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FC9R",
            amount: "46307.0800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHOQ",
            amount: "4504.2200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0325",
            amount: "129521.1200",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FATH",
            amount: "1402.7800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TG73",
            amount: "346593008.0790",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "1829",
            amount: "4807.7500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FH49",
            amount: "281.2900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FGMQ",
            amount: "4091.0500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "TG74",
            amount: "182646485.7652",
            taSystem: "F",
            ta: "FPRS",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "OEKN",
            amount: "226466.6700",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2361",
            amount: "413355.5100",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "2363",
            amount: "146514.7900",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHSM",
            amount: "30311.3800",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHQ9",
            amount: "189654.1500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "FHAP",
            amount: "28043.8500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "0069",
            amount: "1474.4500",
            taSystem: "B",
            ta: "FBSI",
          },
          {
            fundName: "TENET 401(K)",
            fundCode: "3228",
            amount: "329288.5000",
            taSystem: "B",
            ta: "FBSI",
          },
        ],
      },
    },
  ];

  constructor() {
    this.expandAndCheckedValues();
  }

  expandAndCheckedValues() {
    this.aseetsResponseData.forEach((element, i) => {
      for (let key in element.taBusSoldID) {
        if (key != "expand") {
          Object.keys(
            element.taBusSoldID[key].map((childElement, childIndex) => {
              childElement = Object.assign(childElement, {
                expand: false,
                checked: false,
              });
            })
          );
        }
      }
    });
  }

  ngOnInit() {
    this.assetsData = this.aseetsResponseData;
    console.log(this.assetsData);
  }

  checkChild(parent_i, i) {
    parent_i[i].expand = !parent_i[i].expand;
    parent_i[i].checked = !parent_i[i].checked;
  }

  // checkSubChild(group_i, parent_i, child_i, i) {
  //   this.arr[group_i].items[parent_i].childs[child_i].subChilds[i].expand =
  //     !this.arr[group_i].items[parent_i].childs[child_i].subChilds[i].expand;
  // }

  checklastChild() {
    this.showData = !this.showData;
  }
}
